server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:web-study.ca7yqvnelwuw.ap-northeast-2.rds.amazonaws.com:3306/security?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

jpa:
  hibernate:
    ddl-auto: update #create update none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  show-sql: true
